### ISSUE TITLE
Add link to main project

### ISSUE THREAD

**Issue by robertsLando** [hassio-addons/addon-zwave2mqtt#1]
Hi, I'm the author of Zwave2Mqtt, I think that would be useful for users a link to the main project to find all docs needed to set up the gateway. 

https://github.com/OpenZWave/Zwave2Mqtt

Thanks :)

<blockquote><img src="https://avatars0.githubusercontent.com/u/7971916?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/OpenZWave/Zwave2Mqtt">OpenZWave/Zwave2Mqtt</a></strong></div><div>Fully configurable Zwave to MQTT gateway and Control Panel using NodeJS and Vue - OpenZWave/Zwave2Mqtt</div></blockquote>

**Comment by frenck** [comment]
Yep! I meant to do that before release, somehow it got lost.

As soon as the first questions dropped I mind was like: aah that is what I forgot 😂

Will update that asap.

**Comment by robertsLando** [comment]
No worries :smile: Thanks for this add on as it will give me more feedbacks and testers ;) 

I have plan to do a gateway coinfig type called "Home Assistant" that will make zwave devices auto dicovered by hass like zegbee2mqtt does but needs some thoughts (also helps would be much appreciated). I think it wouldn't be so difficult to do, I have added the todo on my readme and also some useful links to existing implementation in zegbee2mqtt that can be used for this as starting point.

**Comment by frenck** [comment]
I've seen you've updated the README with the intention to add that 👍 

I'll be opening some feature requests soon, since a couple of things can be improved that would allow the add-on to integrate tighter with Home Assistant (besides auto-discovery).

**Comment by riemers** [comment]
@robertsLando if you need a tester, just let me know. I have 50+ zwave devices and dying to get zwave detached from HA.

**Comment by robertsLando** [comment]
I need as many testers as possible :) any feedback is more than welcome!

**Comment by RomRider** [comment]
I'd be very happy to test this also! But for now without auto discovery it's not an option, I have too many devices 😊
Also I'd suggest to update to the version 1.1.2 of zwave2mqtt as it's currently impossible to connect to ssl enabled mqtt servers. I've built a local addon based on the new version and it's fixed with 1.1.2.
