### ISSUE TITLE
Custom Components

### ISSUE THREAD

**Issue by Munsio** [hassio-addons/addon-zwave2mqtt#11]
# Problem/Motivation
I use this addon with a couple of Eurotronics SpiritZ DVRs and the auto discovery of zwave2mqtt does not support complex types like `climate` or `fans`.
But they offer the `custom components` where you can define it.
https://github.com/OpenZWave/Zwave2Mqtt#custom-components

## Proposed changes
I see two possible solutions for this:
1) I submit the spirit Z configuration directly to zwave2mqtt and wait until it got merged and the addon got it's update.

2) I would suggest to copy the `device.js` file on build into a mapped folder and symlink it back to `hass/devices.js`

If the second proposal looks acceptable i would like to offer an PR for this

<blockquote><img src="https://avatars0.githubusercontent.com/u/7971916?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/OpenZWave/Zwave2Mqtt">OpenZWave/Zwave2Mqtt</a></strong></div><div>Fully configurable Zwave to MQTT gateway and Control Panel using NodeJS and Vue - OpenZWave/Zwave2Mqtt</div></blockquote>

**Comment by Munsio** [comment]
They added the spirit z wave plus thermostat to their devices.js but the file itself is not customize able in the docker setup, so solution 1 is already fixed but looking forward for solution 2 to be added.

**Comment by bsmeding** [comment]
Same here. I’ve forrest shuttle cover but it identified by light.dimmer. 
If devices.js is editable outside the container it can be fixed
