### ISSUE TITLE
user/pass

### ISSUE THREAD

**Issue by safimahe** [hassio-addons/addon-zwave2mqtt#12]
# Problem/Motivation
webif asking for user/pass
> (Why the issue was filed)

## Expected behavior
documentation to provide default user/pass
> (What you expected to happen)
to login with default credntials
## Actual behavior
the opposite
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Use your HA credentials

**Comment by frenck** [comment]
The add-on badges show an AUTH badge. Whenever an add-on shows that, it means it is using Home Assistant authentication (Pro-tip: click on the badges displayed on an add-on to learn more about them).
