### ISSUE TITLE
add socat

### ISSUE THREAD

**Issue by y1ann1s** [hassio-addons/addon-zwave2mqtt#14]
# Problem/Motivation

> need to run the addon remotely

## Expected behavior

>add socat support 

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

please add socat support to connect to zwave stick remotely

**Comment by frenck** [comment]
Sorry, that is out of scope for the add-on.
Nevertheless, thank you for your suggestion.
