### ISSUE TITLE
Unable to open WebUI

### ISSUE THREAD

**Issue by BarBaar44** [hassio-addons/addon-zwave2mqtt#16]
# Problem/Motivation

Unable to open WebUI after initial installation

## Expected behavior

Have access to the WebUI

## Actual behavior

Webpage gives an empty response

## Steps to reproduce

Do a fresh install of the plugin, version 0.4.1.
See logging below
``
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Z-Wave to MQTT
 Fully configurable Z-Wave to MQTT gateway and control panel
-----------------------------------------------------------
 Add-on version: 0.4.1
 You are running the latest version of this add-on.
 System: HassOS 2.12  (aarch64 / odroid-c2)
 Home Assistant version: 0.102.2
 Supervisor version: 192
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] zwave2mqtt.sh: executing... 
[cont-init.d] zwave2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:26:23] INFO: Starting the Z-Wave to MQTT...
2019-11-28T17:26:25.068Z z2m:Store settings.json not found
2019-11-28T17:26:25.081Z z2m:Store scenes.json not found
2019-11-28T17:26:25.084Z z2m:Store nodes.json not found
2019-11-28T17:26:30.894Z z2m:App Application path:/opt
2019-11-28T17:26:30.912Z z2m:Gateway Gateway needs both MQTT and Zwave Configuration to work
2019-11-28T17:26:31.179Z z2m:App Listening on port 44920
[18:26:31] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
``

<blockquote><img src="https://avatars0.githubusercontent.com/u/7390180?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/openresty/luajit2">openresty/luajit2</a></strong></div><div>OpenResty's Branch of LuaJIT 2. Contribute to openresty/luajit2 development by creating an account on GitHub.</div></blockquote>
<blockquote><div><strong><a href="https://openresty.org/en/download.html">OpenResty - Download</a></strong></div></blockquote>

**Comment by frenck** [comment]
:(

This is an old bug that I originally fixed in Alpine Linux. I'm not sure why it returned. I need to find some serious time to investigate this, as it is not an easy fix.

**Comment by BarBaar44** [comment]
Sorry to hear that. Let me know when I can help..

**Comment by sensei73** [comment]
Thanks in advance, I'm also experiencing it!
