### ISSUE TITLE
MQTT Connection Issue after changing settings

### ISSUE THREAD

**Issue by nellering** [hassio-addons/addon-zwave2mqtt#17]
# Problem/Motivation

Changing MQTT settings causes the addon to no longer connect to MQTT.

## Expected behavior

Settings can be changed without restarting after.  

## Actual behavior

Logs show issues connecting to MQTT after changing MQTT settings.  Restarting the add-on seems to fix the problem.

```
2019-11-29T17:16:08.908Z z2m:Zwave zwave node 27: changed: 49-1-1:Temperature:19.4 -> 19.4
2019-11-29T17:16:08.909Z z2m:Mqtt Error while publishing a value client disconnecting
OpenZWave Detail, Node027, Received: 0x01, 0x0c, 0x00, 0x04, 0x00, 0x1b, 0x06, 0x31, 0x05, 0x01, 0x22, 0x00, 0xc2, 0x3f
OpenZWave Detail,
OpenZWave Info, Node027, Received SensorMultiLevel report from node 27, instance 1, Temperature: value=19.4C
OpenZWave Detail, Node027, Refreshed Value: old value=19.4, new value=19.4, type=decimal
OpenZWave Detail, Node027, Changes to this value are not verified
OpenZWave Detail, Node027, Notification: ValueChanged
```

## Steps to reproduce

1. Click on settings
2. Change a setting in MQTT and click save.
3. Go to logs, see error "z2m:Mqtt Error while publishing a value client disconnecting"

## Proposed changes

Unknown - It seems to be related to this: [https://github.com/OpenZWave/Zwave2Mqtt/issues/64](url)

**Comment by riemers** [comment]
Seeing the same when changing a setting. In my case it shows in the logs it stopped the stick. Above issue referred has incorrect link, presume https://github.com/OpenZWave/Zwave2Mqtt/issues/64#issuecomment-517580349 is the answer. Have not verified myself yet.

**Comment by julien-w** [comment]
Same problem here ...
<img width="695" alt="Capture1" src="https://user-images.githubusercontent.com/2014278/72328964-33d79100-36b4-11ea-9693-de51f81a0c89.PNG">

**Comment by frenck** [comment]
v0.5.0 is released, does that improve things?
