### ISSUE TITLE
Adjusting HASS Discovery Topic does not update on existing nodes

### ISSUE THREAD

**Issue by Flight777** [hassio-addons/addon-zwave2mqtt#18]
# Problem/Motivation

At first set-up I’ve called the MQTT topic “ zwave2mqtt” and left the HASS discovery topic setting blank, thus it would use the general MQTT topic. However, I wanted to change the discovery topic to “ homeassistant”. This is all well, but it does not update the discovery topic for existing nodes, even not when I click “Rediscover” it retains the old discovery topic.

## Expected behavior

After click “Rediscover” on existing nodes that it would update the discovery topic to the latest on as set in the Settings tab.

## Actual behavior

Retains “old” discovery topic and does not update it on existing nodes.

## Steps to reproduce

See above.

## Proposed changes

Ensure the discovery topic is updated after clicking “Rediscover”

**Comment by frenck** [comment]
This is unfortunately not in control of the add-on.
The add-on wraps an existing application, please report this issue upstream:
<https://github.com/OpenZWave/Zwave2Mqtt>

Thanks! 👍
