### ISSUE TITLE
Mount a z-wave dongle by /dev/serial/by-id not working

### ISSUE THREAD

**Issue by magpern** [hassio-addons/addon-zwave2mqtt#21]
# Problem/Motivation
I use usbip to broadcast by dongles to the server. Very often the tty* change when using usbip.

usbip can broadcast the usb device on insert and removal, but often the tty device name change. ttyUSB0 next time it is ttyUSB1 and then back to ttyUSB0. This depends on the reboot order and how many reboots.

## Expected behavior
In zwave2mqtt I can only select tty* devices, not /dev/serial/by-id/xxxxxxxxxx devices.
If I type a /dev/serial/by-id/xxxxxxx device in the field, zwave2mqtt cannot open it.

## Actual behavior
2019-12-24 00:48:09.197 Info, Trying to open serial port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A9M9DV3R-if00-port0 (attempt 1)
2019-12-24 00:48:09.232 Info, Serial port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A9M9DV3R-if00-port0 opened (attempt 1)

It simply fails. But if I change to ttyUSB0 it works (but the it could be ttyUSBx)

## Steps to reproduce
Just endter a /dev/serial/by-id/ serial id.

## Proposed changes
When i ssh into the docker container I can list the /dev/serial/by-id
but I see they have no link to the actual tty device, which they normally do in linux.

`root@a0d7b954-zwave2mqtt:/$ ls -la /dev/serial/by-id/
total 0
drwxr-xr-x    2 root     root           120 Dec 24 00:56 .
drwxr-xr-x    3 root     root            60 Dec 24 00:56 ..
crw-rw----    1 root     dialout   188,   2 Dec 24 00:56 usb-1a86_USB2.0-Serial-if00-port0
crw-rw----    1 root     dialout   188,   3 Dec 24 00:56 usb-FTDI_FT232R_USB_UART_A9M9DV3R-if00-port0
crw-rw----    1 root     dialout   166,   2 Dec 24 00:56 usb-MySensors.org_Sensebender_GW_E8B45813514D355231202020FF18142B-if00
crw-rw----    1 root     dialout   166,   0 Dec 24 00:56 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00193672AA-if00`

Expected is:

`magpern@plexserver:~$ ls -la /dev/serial/by-id
total 0
drwxr-xr-x 2 root root 120 Dec 23 23:45 .
drwxr-xr-x 4 root root  80 Dec 23 23:37 ..
lrwxrwxrwx 1 root root  13 Dec 23 23:45 usb-1a86_USB2.0-Serial-if00-port0 -> ../../ttyUSB2
lrwxrwxrwx 1 root root  13 Dec 23 23:45 usb-FTDI_FT232R_USB_UART_A9M9DV3R-if00-port0 -> ../../ttyUSB3
lrwxrwxrwx 1 root root  13 Dec 23 23:45 usb-MySensors.org_Sensebender_GW_E8B45813514D355231202020FF18142B-if00 -> ../../ttyACM2
lrwxrwxrwx 1 root root  13 Dec 23 23:38 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B00193672AA-if00 -> ../../ttyACM0
`

**Comment by sensei73** [comment]
Would be great, I use Zwave and Zigbee. When rebooting sometimes /dev/ttyACM0 and /dev/ttyACM1 get inverted... Will fix that with zwave2mqtt (zigbee2mqtt you can use "/dev/serial/by-id"). Thanks in advance

**Comment by frenck** [comment]
Just tested this with v0.5.0 and worked for me now :)

**Comment by cd334** [comment]
For me not worked. On the list I cannot see the /dev/serial/by-id/xxxxxxx and if I copy it manually and save the configuration, refresh the page, the value is restored to /dev/ttyACMx
