### ISSUE TITLE
Enable ozw 1.6 in HA plugin

### ISSUE THREAD

**Issue by craigrallen** [hassio-addons/addon-zwave2mqtt#26]
# Problem/Motivation
How to enable ozw1.6, the default in the HA plugin is ozw1.4. Ozw1.4 is no longer supported by the developer and he advised to use 1.6 to fix some discovery issues and bugs. 

> (Why the issue was filed)

Discovery of newer devices already supported in ozw1.6, but the definition files will never be added to ozw1.4 because the developer is no longer working on 1.4 and is now working on ozw1.8 

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Already implemented on dev, is part of the next release.
