### ISSUE TITLE
Feat: Update openzwave db to include z-dim

### ISSUE THREAD

**Issue by sebastian-steinmann** [hassio-addons/addon-zwave2mqtt#27]
# Problem/Motivation
Update the openzwave db to rev 7ad4c22f4f3f78bad84a46de8a26906e35b28329 to include new z-dim component from Heatit

## Expected behavior

My z-dim component is recognized and can be configured.

## Actual behavior

Z-Dim component is unknown

## Steps to reproduce

1. Get a Heatit Z-Dim
2. Try to include it

## Proposed changes

Update the openzwave db to rev 7ad4c22f4f3f78bad84a46de8a26906e35b28329

**Comment by sebastian-steinmann** [comment]
This is fixed now? Just need a release?

**Comment by frenck** [comment]
It is not "just" a release, there are pretty darn big changes in here that need to be tested.

**Comment by sebastian-steinmann** [comment]
Anything the community can do to help with testing?

**Comment by frenck** [comment]
Yes, have patience

**Comment by frenck** [comment]
v0.5.0 is released.
