### ISSUE TITLE
Removing or Renaming a device, doesn't cleanup at HASS

### ISSUE THREAD

**Issue by billiaz** [hassio-addons/addon-zwave2mqtt#29]
When a New device is discovered, if for any reason is been excluded from zwave2mqtt. The device gives no option to remove it from HomeAssistant.

The same happens when a device is renamed, or changed name in zwave2mqtt frontend (web ui). 
Then I do see two times the same device.

There should be a way to cleanup the remove/renamed devices from HomeAssistant.

1. Restart doesn't help
2. Entities can be deleted but still left with empty devices.

**Comment by frenck** [comment]
Correct, it is still in MQTT, you would have to clean up the topic manually or report a feature request at the upstream Zwave2mqtt project by the openzwave organization.
