### ISSUE TITLE
Add - inclusion - is not adding securely

### ISSUE THREAD

**Issue by cts1085** [hassio-addons/addon-zwave2mqtt#31]
# Problem/Motivation

I am in the process of adding some new devices to my zwave mesh and the UI is not prompting for Secure inclusion - I raised this concern on zwave2mqtt and was told this is not a problem with zwave2mqtt so I am entering it here

## Expected behavior

I know my Key is correct because previously added devices are showing as "Yes" secure in the list, but when I add new devices (ZSE40 Sensor, Aeotec NanoMote, Inovelli Red Series Dimmer) they are not being prompted to add securely.  The pop-up prompt is expected per zwave2mqtt

## Actual behavior

Devices are being added but not using secure protocols which cause some of the functionality to be 
reduced.

## Steps to reproduce

remove - exclude device that was secure, then wait a while - add - inclusion - and it is not prompting for secure add.

## Proposed changes

No workarounds are known at this point. 

I am running HassOS 3.11 on a Raspberry PI B+, Supervisor 206 and Add-on Zwave2MQTT 0.5.0

**Comment by frenck** [comment]
Hi!

Add-ons wrap existing software, in this case, zwave2mqtt. We don't modify the working of that software and don't maintain that either.

Please report your issue with the OpenZwave Mqtt2Zwave project. Thanks 👍

**Comment by cts1085** [comment]
Sounds good - I will
