### ISSUE TITLE
Stop responding every day

### ISSUE THREAD

**Issue by soerensteen** [hassio-addons/addon-zwave2mqtt#33]
# Problem/Motivation

After I updated to the latest version my devices stop working almost every day and I have to restart the zwave2mqtt add-on.
Sometimes I cannot even open the web UI

On the previous version it's been Rock solid for months.

## Expected behavior

Working without interruptions

## Actual behavior

Stops working

## Proposed changes

Fix

**Comment by phillipgreenii** [comment]
I believe I'm suffering a similar problem.  I upgraded and now things are going crazy.  Sometimes things show in zwave2mqtt, sometimes they don't.  Sometimes it has the correct type, other times it is unknown, still other times it just shows ().  With all of this craziness, homeassistant only ever sees unavailable for each device.  As far as I can tell, when things are showing in zwave2mqtt, the mqtt is getting updated. I'm running homeassistant on a NUC and using aeotec Z-Stick Gen 5.

**Comment by trubacca** [comment]
I'm glad to see another ticket for this as I too am experiencing this, even if it seems pretty rare.
I'm still trying to determine any correlations or causes, but it seems to stop responding randomly.. no more device/mqtt updates, and the dashboard just spins.

I'm running a fully updated Hassio on a RP4 using a Nortek Zwave+ZB adapter. Zigbee still seems to work fine when Zwave stops. 

I have a handful of power-adapter/monitors and sensors in a small space, no dead spots, but I also often struggle with device health and stuck values. I think that is a different issue but it makes it tricky to isolate the trouble. Not sure if the recent work on the OpenZWave integration would make that a more stable alternative but I still wish for the advantages of a separate implementation. Might end up moving this entire setup to the server that runs my MQTT broker and split the entire zwave/zigbee controller logic out of Hassio.

I'll try and dump some logs next time I see it happen, though work has been keeping me busy and I have had limited time to invest to troubleshooting (dangerous circumstances when using Hassio it seems, lol). Thanks!
