### ISSUE TITLE
MQTT messages sent

### ISSUE THREAD

**Issue by GieBek** [hassio-addons/addon-zwave2mqtt#45]
Hey,

After uninstalling zwave2mqtt, MQTT messages are sent all the time. When I listen to topics, the HA page can hang for a few seconds. I can't go to the Supervisor tab and restart the raspberry, I need to disconnect the power supply and connect again.

Without listening for messages Home Assistant works fine.
The system crashes when trying to listen for the first time.
Home Assistant installed on Docker

Please help.

![Adnotacja 2020-03-30 000927](https://user-images.githubusercontent.com/9890042/77862281-bfc07a00-721a-11ea-992e-4dacdfed41a9.jpg)

**Comment by Munsio** [comment]
@GieBek you can see that on all messages it says "Retain: true" so regardless if you uninstall zwave2mqtt or not all those messages will stay in MQTT until you delete them. (Thats a MQTT functionality not zwave2mqtt or homeassistant)

You can use something like: https://github.com/thomasnordquist/MQTT-Explorer to inspect your mqtt broker and delete the unwanted items.

**Comment by frenck** [comment]
@Munsio Is actually correct. The messages are retained in MQTT, which is not an issue of the add-on.

Please clean up your MQTT broker.
