### ISSUE TITLE
Updated message is incorrect

### ISSUE THREAD

**Issue by P-Verbrugge** [hassio-addons/addon-zwave2mqtt#48]
I noticed the add-on says there is a new version available when you start it:
 Add-on version: 0.5.0
 There is an update available for this add-on!
 Latest add-on version: null

However, the new version is null. Seems incorrect to me.

## Expected behavior

I expected no update message.

> (What you expected to happen)

The logs says there is a new version available but there isn't any.

**Comment by frenck** [comment]
This is fixed in 0.6.0
