### ISSUE TITLE
Map database path to accessible folder?

### ISSUE THREAD

**Issue by schmittx** [hassio-addons/addon-zwave2mqtt#50]
I'm new to Docker environments in general so my apologies in advance if this is a stupid question...

My setup = very standard; HassOS 3.13 image on a RPi 3B+, Aeotec Gen5 stick, and this add-on.

Everything is working great but I'd like to use my own modified version of the OpenZWave database (for specific device configs).

I know I can specify the database path within Z2M, but I don't know how to map that path to an accessible folder within Home Assistant (i.e. `addons`, `share`, etc.). Can anyone help?

**Comment by Munsio** [comment]
I would suggest to use `share`. The `share` folder is directly mapped into the root directory of the container so in Z2M in the config just define the path to something like `/share/myCustomDatabase` and it should work.

**Comment by schmittx** [comment]
Perfect, exactly what I was looking for! I just confirmed that this works, thanks so much for the help!
