### ISSUE TITLE
No configuration for FIBARO FGRM222

### ISSUE THREAD

**Issue by Oohcalme** [hassio-addons/addon-zwave2mqtt#51]
# Problem/Motivation

There is no configuration visible in the Configuration panel for the roller shutter Fibaro FGRM222
But in the main panel the FGRM222 are rigthly identified with the constructors name

## Expected behavior

Get the parameters visible in order to update them. It worked before, I can't say if it is link to a particular release or not

## Actual behavior

nothing visible in the Configuration node

Thanks !
I don't know if it is related to the addon or the zwave lib... sorry if i'm not in the wrong depository...

**Comment by frenck** [comment]
The database is imported from the OpenZWave project and not maintained here.

**Comment by Oohcalme** [comment]
But the database is ok. I just check again and I see the device with the right identifier.
And again, it was working before and I do have the auto update database activated.

So what can I do ?
