### ISSUE TITLE
very old zwave2mqtt - can this be updated?

### ISSUE THREAD

**Issue by sanderlv** [hassio-addons/addon-zwave2mqtt#53]
This addon used 3.0.2.

There are a lot of improvements for zwave2mqtt. Could this please be brought to the addon?

https://github.com/OpenZWave/Zwave2Mqtt/releases

<blockquote><img src="https://avatars0.githubusercontent.com/u/7971916?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/OpenZWave/Zwave2Mqtt">OpenZWave/Zwave2Mqtt</a></strong></div><div>Fully configurable Zwave to MQTT gateway and Control Panel using NodeJS and Vue - OpenZWave/Zwave2Mqtt</div></blockquote>

**Comment by frenck** [comment]
Feel free to help out!

**Comment by sanderlv** [comment]
Hi Frenck, if I knew where ot start and was able to, I was willing to... but I am just an very enthusiast user.

**Comment by frenck** [comment]
In that case, it will be picked up on the next round of maintenance.

**Comment by sanderlv** [comment]
When will that be Frenck? Thank you for this awesome work!
