### ISSUE TITLE
zwave2mqtt versioning and update

### ISSUE THREAD

**Issue by sanderlv** [hassio-addons/addon-zwave2mqtt#54]
https://github.com/hassio-addons/addon-zwave2mqtt/commit/7f3612ece010fc82f637cdc57bc82533b41f7131

Since Frenck point me to somewhere I do not know where in above post:
Please see where to get support and questions in general. Thanks.

I must have to open another issue. Since I do NOT know where to go for support and I am really looking for help on an update openzwave and zwave2mqtt pacakge... I am running the addon in hassos and this tells me the version is:
![image](https://user-images.githubusercontent.com/16528916/81483408-2aaf9880-923e-11ea-9a1c-bfe2244715ad.png)
And I am up to date everywhere... Wehere and how can I get "support" Frenck? Please point me in the right direction or help me :-).

Thank you.

**Comment by sinclairpaul** [comment]
The addon has not been released with 3.0.3 yet.  There is no specific timescale.

You can track the details of releases at https://github.com/hassio-addons/addon-zwave2mqtt/releases
