### ISSUE TITLE
Proposal: Add Socat

### ISSUE THREAD

**Issue by joe8mofo** [hassio-addons/addon-zwave2mqtt#57]
Proposing that socat be added to the container. Then allow a variable to be passed to call socat on boot before the zwave daemon starts.

An example socat call would be:
socat PTY,link=/dev/zwave,raw,group=root,mode=777 TCP:<IPADDRESS>:7676

We would want to pass <IPADDRESS> as a variable.

This would enable people to use zwave as serial devices over IP. If someone had a zwave stick on a raspberry pi or maybe they have a vera; this would enable the device to be passed to the zwave2mqtt addon.

**Comment by natwilson** [comment]
+1 I run Home Assistant within Hyper-V so no direct access to local ports.  My Z-wave stick is on  Raspberry Pi.

**Comment by joe8mofo** [comment]
Noone is looking at this request. This shouldn't be stale.

**Comment by frenck** [comment]
I'm not adding this level of logic to the add-ons.
In general, if you need these solutions, it would be better to run ZWave2MQTT itself on a separate device.
