### ISSUE TITLE
Difference with ozwdaemon

### ISSUE THREAD

**Issue by sensei73** [hassio-addons/addon-zwave2mqtt#58]
Sorry to post here, It's not a issue.

But since 0.110 there is another "official zwave implantation and I am lost!

What is the difference with ozwdaemon
https://github.com/marcelveldt/hassio-addons-repo/tree/master/ozwdaemon

Thanks in advance, and sorry to ask!

<blockquote><img src="https://avatars2.githubusercontent.com/u/6389780?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/marcelveldt/hassio-addons-repo">marcelveldt/hassio-addons-repo</a></strong></div><div>Marcelveldt's repo with hassio add-ons. Contribute to marcelveldt/hassio-addons-repo development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
It is not related. This add-on allows you to use general MQTT, and structure it yourself.
