### ISSUE TITLE
panel: Controller action "Refresh node info" does not work in panel UI

### ISSUE THREAD

**Issue by j9brown** [hassio-addons/addon-zwave2mqtt#60]
# Problem/Motivation

The "Refresh node info" controller action in the control panel does not seem to work when the UI is embedded as a panel in Home Assistant.

When not embedded, the zwave2mqtt will display an alert dialog prompting for a node id.  When embedded, no alert appears.

## Expected behavior

I expected to be prompted for the node to refresh.

## Actual behavior

Nothing appeared to happen.  There were no messages emitted in the OZW log.

## Steps to reproduce

Configure zwave2mqtt to display as an embedded iframe in Home Assistant.

panel_iframe:
  # Z-Wave to MQTT
  zwave2mqtt:
    title: Z-Wave to MQTT
    icon: mdi:z-wave
    url: http://home-assistant.lan:8091

Using the Chrome web browser, open the zwave2mqtt control panel in Home Assistant, select the "Refresh node info" controller action near the top of the page, click the "send arrow" icon to invoke it.

**Comment by j9brown** [comment]
It seems there may be some related issues with other actions.  For example, "export nodes" doesn't actually initiate a download of the nodes.json file when invoked inside an iframe.

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the zwave2mqtt project. Please report this issue upstream. Thanks 👍
