### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by satellite-no** [hassio-addons/addon-zwave2mqtt#63]
Fresh install. Install successful. Start fails

[cont-init.d] nginx.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...

**Comment by frenck** [comment]
This log is incomplete.

**Comment by frenck** [comment]
No complete logs or issues supplied after 12 days. Closing issue.
