### ISSUE TITLE
GE/enbrighten switches

### ISSUE THREAD

**Issue by benchdog93** [hassio-addons/addon-zwave2mqtt#65]
# Problem/Motivation
When adding name in control panel switches are disabled. Dimmer does not retain its position.  The way I would expect the dimmer to work would be a single click on, set brightness, and a single click off. At least that how they worked with past integrations.

Not sure how to fix this

Z-Wave to MQTT
Current version: 0.8.1 (changelog)

14292 In-Wall Smart Toggle Switch (GE (Jasco Products))
14295 In-Wall Smart Toggle Dimmer (GE (Jasco Products))

Thank you for your help.

**Comment by frenck** [comment]
This is not an issue the add-on can solve.

Add-ons wrap existing software, in this case, zwave2mqtt by the openzwave project. Please report your issue with them. As soon as they patch/fix it, it will end up in this add-on as well.
