### ISSUE TITLE
After upgrade to 0.8.3 after restart of HA Z-Wave devices remain unavailable

### ISSUE THREAD

**Issue by lendy007** [hassio-addons/addon-zwave2mqtt#66]
# Problem/Motivation

After I have upgraded to 0.8.3 when I restart HA (0.118.4) all the time all my Z-Wave device remains unavailble. In log of Z-Wave to MQTT I see that it is comunicating with nodes and other stuff. After I restart also Z-Wave to MQTT via supervisor it takes another few minutes, but nodes will appear online. 

Is somebody else experiencing similar issue, or are there any hints how to troubleshoot it?

Thank you

**Comment by frenck** [comment]
This has generally something to do with the retain settings of MQTT messages.
Depends a bit on how you've set it up and used it.
