### ISSUE TITLE
ZXT-600 dont show climate entity

### ISSUE THREAD

**Issue by eonnet** [hassio-addons/addon-zwave2mqtt#68]
# Problem/Motivation

When i include ZXT-600 the climate component is not shown, only temperature_air and battery_level, when i include it powered by usb it shows only the temperature_air object. When i go to zwave2mqtt control panel in user tab i can send climate commands vie the web ui.
## Expected behavior

Climate object to be shown

## Actual behavior

Climate object not showing
## Steps to reproduce

Include the ZXT-600 
## Proposed changes

Add climate component to autodiscovery

**Comment by frenck** [comment]
Please report the issue with the OpenZwave project, at that is where the definition come from 👍
