### ISSUE TITLE
Zwave2MQTT v2.0.2 released

### ISSUE THREAD

**Issue by robertsLando** [hassio-addons/addon-zwave2mqtt#7]
https://github.com/OpenZWave/Zwave2Mqtt/releases/tag/v2.0.2

**Comment by frenck** [comment]
Hey @robertsLando, Thanks for the notification.
I do appreciate those, but we automatically receive notifications already (spares you the effort). 😉

**Comment by robertsLando** [comment]
Perfect sorry for this will stop creating issue so :)

Daniel
