### ISSUE TITLE
Web uit does not open

### ISSUE THREAD

**Issue by gjvetten** [hassio-addons/addon-zwave2mqtt#86]
Hello,

I want to move to Z-Wave integration Z-Wave to MQTT. Installed the add-on, updated config.yaml, but web ui does not open. H/W is NUC running Proxmox / HA.

Yaml looks like:

```yaml
# Duckdns
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Zwave
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
```

Log looks like:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Z-Wave to MQTT
 Fully configurable Z-Wave to MQTT gateway and control panel
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (amd64 / qemux86-64)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] zwave2mqtt.sh: executing... 
[cont-init.d] zwave2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[20:07:59] INFO: Starting the Z-Wave to MQTT...
[services.d] done.
2021-01-29T19:08:00.156Z z2m:Store settings.json not found
2021-01-29T19:08:00.162Z z2m:Store scenes.json not found
2021-01-29T19:08:00.162Z z2m:Store nodes.json not found
2021-01-29T19:08:00.545Z z2m:App Zwave2Mqtt version: 4.1.1
2021-01-29T19:08:00.545Z z2m:App Application path:/opt
2021-01-29T19:08:00.606Z z2m:Gateway Zwave settings are not valid
2021-01-29T19:08:00.751Z z2m:App Listening on port 44920
[20:08:01] INFO: Starting NGinx...
```

Any suggestions? Help is welcome. Thanks in advance.

GJ

**Comment by frenck** [comment]
```
zwave:
usb_path: /dev/serial/by-id/usb-0658_0200-if00
``` 

that is not a valid configuration for this add-on. Not sure what you are trying to do.

**Comment by frenck** [comment]
`[20:08:01] INFO: Starting NGinx...`

☝️ That is the last message. All is fine.

> "Web UI does not open"

What does that mean? Do you get an error? Anything in the Supervisor logs?
Anything in the Home Assistant logs?

**Comment by gjvetten** [comment]
Hello Frenck,

That's a quick reply. Thanks. I've removed zwave: usb_path: /dev/serial/by-id/usb-0658_0200-if00. 

Log shows:
21-01-29 19:41:06 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_a0d7b954_zwave2mqtt application
21-01-29 19:41:10 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_zwave2mqtt application
21-01-29 19:41:10 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/zwave2mqtt/amd64 with version 0.9.0

HA version Home Assistant OS 5.10 running on Proxmox. Web ui does not open (https://------.duckdns.org:8091)

GJ

**Comment by frenck** [comment]
That is correct, this add-on uses ingress, so indeed that won't work on that port.

**Comment by gjvetten** [comment]
Hmm. I've opened via the web UI button. I'm afraid this requires extra study and documentation to understand.

**Comment by gjvetten** [comment]
Got it working. With local IP adres. Thanks Frenck for all help.
