### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by darkbasic** [hassio-addons/addon-zwave2mqtt#9]
# Problem/Motivation

Despite entering the same user and the same password used by Home Assistant the login fails.

## Expected behavior

It successfully logs in.

## Actual behavior

Re-asks for the credentials.

## Steps to reproduce

I don't know if it's possible to reproduce it. It worked the very first time, then I had to pull the power from the pi and at the next boot it didn't work anymore.
I tried to remove the docker image and reinstall the hassio addon, but nothing changed.
It works with leave_front_door_open.
Nothing interesting can be found in the logs, even with `"log_level": "info"`

## Proposed changes

None.

**Comment by andreasfelder** [comment]
I have this same issue starting yesterday. It seemed to have started when the hassio supervisor was auto updated yesterday. Just FYI unsure if related the local DNS resolution was broken with this update as well.

**Comment by MorpheusRO** [comment]
Same issue here... Also other addons are behaving the same when accessed directly through IP:PORT.
The DNS issue was solved today in 180 Supervisor, but this issue persists...

**Comment by sinclairpaul** [comment]
Please update to the Hass.io supervisor v181 and retest. The issue should be resolved.
