### ISSUE TITLE
Thermofloor Heatit Z-TRM3 wrong sensor showing

### ISSUE THREAD

**Issue by espen4001** [hassio-addons/addon-zwave2mqtt#98]
# Problem/Motivation

Using ZWave to MQTT in docker container alongside HomeAssistant in another container. When adding my Thermofloor Heatit Z-TRM3 thermostate to ZWave, it shows up in Home Assistant as expected. This thermostate har multiple sensor modes: 

![image](https://user-images.githubusercontent.com/38804642/108474543-d1c26580-728f-11eb-83de-c0dd43df57f3.png)

And based on the selected mode, one of 3 multilevel sensors are used to control the temperature based on setpoint:

![image](https://user-images.githubusercontent.com/38804642/108474759-177f2e00-7290-11eb-975d-64803ef75c50.png)

Sensor 2-49-2 is the internal sensor.
Sensor 2-49-3 is depends on an external connected sensor, which I don't have, hence the value "0" from this sensor.
Sensor 2-49-4 is the connected floor sensor.

But regardless of which "Sensor mode" the thermostate is set to, the measured temperature value in the climate-entity in HomeAssistant is shown from sensor 2-49-2, which is the internal sensor.

I have selected sensor mode "F", Floor mode, which uses the floor sensor. Everthing works fine - my setpoint is 31,5 ºC, and the thermostates regulates to this and using the floor sensor. But the shown value in Home Asisstant is wrong.

![image](https://user-images.githubusercontent.com/38804642/108476035-d6881900-7291-11eb-8471-27e7ad6d6bbb.png)

## Expected behavior

Shown value in Home Assistant to change based on selected sensor mode.

## Actual behavior

Sensor 2-49-2 is shown, regardless of selected mode.

## Steps to reproduce

I have 2 identical units, both with the same issue.

## Proposed changes

I recently changed from using the OpenZwave(Beta) integration in Home Assistant and the Ozwdaemon to manage the zwave network. With this setup, the values were shown as expected. Changing sensor mode also changed which value was shown in frontend.

**Comment by frenck** [comment]
Hi there @espen4001!


Thanks for the extensive report! However, there is unfortunately not much I can do with it.

Add-ons wrap existing software, in this case zwave2mqtt. Therefore the application itself is not maintained by us.

Please report your issue upstream (copy this issue, as the detail is great!)

Sorry I don't have more satisfying answer for you.

../Frenck
